### ISSUE TITLE
Version 6.0.0-beta.2 fails at render when used as a external dependency

### ISSUE THREAD

**Issue by lmiguelmh** [iamstevendao/vue-tel-input#279]
Using the latest version as an external dependency (6.0.0-beta.2 at the time of this writing):

```
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/vue-tel-input"></script>
<link rel="stylesheet" href="https://unpkg.com/vue-tel-input/dist/vue-tel-input.css" />
...
<vue-tel-input v-model="value"></vue-tel-input>
```

Fails with:

```
[Vue warn]: Error in render: "TypeError: Object(...) is not a function"
...
TypeError: Object(...) is not a function
```

A workaround is to use version 5.6.1.
```
<script src="https://unpkg.com/vue-tel-input@5.6.1/dist/vue-tel-input.umd.min.js"></script>
```
![image](https://user-images.githubusercontent.com/3931964/128890371-5da79bc7-30ea-4ebc-9e0e-ecb3a98f4b5f.png)

**Comment by iamstevendao** [comment]
@lmiguelmh it's fixed now. the latest version is `v5.6.1`

**Comment by Dropcodee** [comment]
i just installed this package with Vue 3 and I am getting this same error, please what can i do

**Comment by Dropcodee** [comment]
runtime-core.esm-bundler.js?6bd5:6123 Uncaught (in promise) TypeError: Cannot read property 'isCE' of null
    at renderSlot (runtime-core.esm-bundler.js?6bd5:6123)
    at Proxy.u (vue-tel-input.umd.min.js?e75b:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:1168)
    at componentEffect (runtime-core.esm-bundler.js?5c40:5214)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:5167)
    at mountComponent (runtime-core.esm-bundler.js?5c40:5126)
    at processComponent (runtime-core.esm-bundler.js?5c40:5084)
    at patch (runtime-core.esm-bundler.js?5c40:4690)
renderSlot @ runtime-core.esm-bundler.js?6bd5:6123
u @ vue-tel-input.umd.min.js?e75b:1
renderComponentRoot @ runtime-core.esm-bundler.js?5c40:1168
componentEffect @ runtime-core.esm-bundler.js?5c40:5214
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
Promise.then (async)
nextTick @ runtime-core.esm-bundler.js?5c40:246
useInsertStyles @ utils.js?2adb:78
IconBase @ IconBase.js?6ba3:44
renderComponentRoot @ runtime-core.esm-bundler.js?5c40:1179
componentEffect @ runtime-core.esm-bundler.js?5c40:5214
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5287
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:155
flushJobs @ runtime-core.esm-bundler.js?5c40:387
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?5c40:287
queueCb @ runtime-core.esm-bundler.js?5c40:309
queuePostFlushCb @ runtime-core.esm-bundler.js?5c40:315
queueEffectWithSuspense @ runtime-core.esm-bundler.js?5c40:1861
scheduler @ runtime-core.esm-bundler.js?5c40:2057
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
scheduler @ reactivity.esm-bundler.js?a1e9:866
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
scheduler @ reactivity.esm-bundler.js?a1e9:866
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
set value @ reactivity.esm-bundler.js?a1e9:776
finalizeNavigation @ vue-router.esm-bundler.js?6c02:3140
eval @ vue-router.esm-bundler.js?6c02:3013
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?6c02:2984
push @ vue-router.esm-bundler.js?6c02:2915
install @ vue-router.esm-bundler.js?6c02:3329
use @ runtime-core.esm-bundler.js?5c40:4022
eval @ main.js?56d7:11
./src/main.js @ app.js:1195
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:1363
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997
Show 307 more frames
runtime-core.esm-bundler.js?6bd5:6123 Uncaught (in promise) TypeError: Cannot read property 'isCE' of null
    at renderSlot (runtime-core.esm-bundler.js?6bd5:6123)
    at Proxy.u (vue-tel-input.umd.min.js?e75b:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:1168)
    at componentEffect (runtime-core.esm-bundler.js?5c40:5214)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:5167)
    at mountComponent (runtime-core.esm-bundler.js?5c40:5126)
    at processComponent (runtime-core.esm-bundler.js?5c40:5084)
    at patch (runtime-core.esm-bundler.js?5c40:4690)
renderSlot @ runtime-core.esm-bundler.js?6bd5:6123
u @ vue-tel-input.umd.min.js?e75b:1
renderComponentRoot @ runtime-core.esm-bundler.js?5c40:1168
componentEffect @ runtime-core.esm-bundler.js?5c40:5214
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
processElement @ runtime-core.esm-bundler.js?5c40:4767
patch @ runtime-core.esm-bundler.js?5c40:4687
componentEffect @ runtime-core.esm-bundler.js?5c40:5221
reactiveEffect @ reactivity.esm-bundler.js?a1e9:42
effect @ reactivity.esm-bundler.js?a1e9:17
setupRenderEffect @ runtime-core.esm-bundler.js?5c40:5167
mountComponent @ runtime-core.esm-bundler.js?5c40:5126
processComponent @ runtime-core.esm-bundler.js?5c40:5084
patch @ runtime-core.esm-bundler.js?5c40:4690
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
processFragment @ runtime-core.esm-bundler.js?5c40:5043
patch @ runtime-core.esm-bundler.js?5c40:4683
mountChildren @ runtime-core.esm-bundler.js?5c40:4874
mountElement @ runtime-core.esm-bundler.js?5c40:4795
Promise.then (async)
nextTick @ runtime-core.esm-bundler.js?5c40:246
mounted @ wave.js?a9d4:39
callWithErrorHandling @ runtime-core.esm-bundler.js?5c40:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:164
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js?5c40:2913
flushPostFlushCbs @ runtime-core.esm-bundler.js?5c40:358
flushJobs @ runtime-core.esm-bundler.js?5c40:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?5c40:287
queueCb @ runtime-core.esm-bundler.js?5c40:309
queuePostFlushCb @ runtime-core.esm-bundler.js?5c40:315
queueEffectWithSuspense @ runtime-core.esm-bundler.js?5c40:1861
scheduler @ runtime-core.esm-bundler.js?5c40:2057
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
scheduler @ reactivity.esm-bundler.js?a1e9:866
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
scheduler @ reactivity.esm-bundler.js?a1e9:866
run @ reactivity.esm-bundler.js?a1e9:183
trigger @ reactivity.esm-bundler.js?a1e9:189
set value @ reactivity.esm-bundler.js?a1e9:776
finalizeNavigation @ vue-router.esm-bundler.js?6c02:3140
eval @ vue-router.esm-bundler.js?6c02:3013
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?6c02:2984
push @ vue-router.esm-bundler.js?6c02:2915
install @ vue-router.esm-bundler.js?6c02:3329
use @ runtime-core.esm-bundler.js?5c40:4022
eval @ main.js?56d7:11
./src/main.js @ app.js:1195
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:1363
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997
Show 170 more frames
3runtime-core.esm-bundler.js?6bd5:6123 Uncaught (in promise) TypeError: Cannot read property 'isCE' of null
    at renderSlot (runtime-core.esm-bundler.js?6bd5:6123)
    at Proxy.u (vue-tel-input.umd.min.js?e75b:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:1168)
    at componentEffect (runtime-core.esm-bundler.js?5c40:5214)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:5167)
    at mountComponent (runtime-core.esm-bundler.js?5c40:5126)
    at processComponent (runtime-core.esm-bundler.js?5c40:5084)
    at patch (runtime-core.esm-bundler.js?5c40:4690)

**Comment by iamstevendao** [comment]
@Dropcodee can you try with `6.0.0-beta.4`?

**Comment by luismarquesfreire** [comment]
> Uncaught (in promise) TypeError: Cannot read property 'isCE' of null
> at renderSlot (runtime-core.esm-bundler.js?6bd5:6123)
> at Proxy.u (vue-tel-input.umd.min.js?e75b:1)
> at renderComponentRoot (runtime-core.esm-bundler.js?5c40:1168)
> at componentEffect (runtime-core.esm-bundler.js?5c40:5214)
> at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
> at effect (reactivity.esm-bundler.js?a1e9:17)
> at setupRenderEffect (runtime-core.esm-bundler.js?5c40:5167)
> at mountComponent (runtime-core.esm-bundler.js?5c40:5126)
> at processComponent (runtime-core.esm-bundler.js?5c40:5084)
> at patch (runtime-core.esm-bundler.js?5c40:4690)

I have 6.0.0-beta.4 and that still happens only in production.

**Comment by matrei** [comment]
I also got TypeError: Cannot read property 'isCE' of null. Upgrading Vue from 3.0.0 to 3.2.6 resolved it for me.

**Comment by damienroche** [comment]
same as @matrei got a TypeError : Cannot read property 'isCE' of null
With Vue 3.0.5

**Comment by blocka** [comment]
I am also having this issue, using vue 3.2.20 and beta.6

**Comment by souvenir-lee** [comment]
For those who are still struggling
I solved it by referring to this.

vue/core issue 
- [#4344(comment)](https://github.com/vuejs/core/issues/4344#issuecomment-912627569)
- [#2064(comment)](https://github.com/vuejs/core/issues/2064#issuecomment-797365133)

The code I modified in `vue.config.js`
```js
const path = require('path')
module.exports = {
  ...
  // for VueTelInput
  configureWebpack: {
    resolve: {
      symlinks: false,
      alias: {
        vue: path.resolve('./node_modules/vue')
      }
    }
  }
}
```

**Comment by leojeg** [comment]
> For those who are still struggling I solved it by referring to this.
> 
> vue/core issue
> 
> * [#4344(comment)](https://github.com/vuejs/core/issues/4344#issuecomment-912627569)
> * [#2064(comment)](https://github.com/vuejs/core/issues/2064#issuecomment-797365133)
> 
> The code I modified in `vue.config.js`
> 
> ```js
> const path = require('path')
> module.exports = {
>   ...
>   // for VueTelInput
>   configureWebpack: {
>     resolve: {
>       symlinks: false,
>       alias: {
>         vue: path.resolve('./node_modules/vue')
>       }
>     }
>   }
> }
> ```

Thank you for this solution. its solve for me
